nelmio_api_doc:
    documentation:
        info:
            title: PrintifyBackendHomework API
            description: Simple API for managing stock and orders
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: Your Json Web Token
                scheme: bearer
                name: Authorization
                in: header
            security:
                - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$)