services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    KacperWojtaszczyk\PrintifyBackendHomework\Tests\Mock\Infrastructure\Repository\Product\ProductRepositoryMock: ~
    KacperWojtaszczyk\PrintifyBackendHomework\Infrastructure\Repository\Product\ProductRepository: '@KacperWojtaszczyk\PrintifyBackendHomework\Tests\Mock\Infrastructure\Repository\Product\ProductRepositoryMock'

    KacperWojtaszczyk\PrintifyBackendHomework\Tests\Mock\Infrastructure\Repository\User\UserRepositoryMock: ~
    KacperWojtaszczyk\PrintifyBackendHomework\Infrastructure\Repository\User\UserRepository: '@KacperWojtaszczyk\PrintifyBackendHomework\Tests\Mock\Infrastructure\Repository\User\UserRepositoryMock'

